CREATE TABLE "USERS"(
  id INTEGER NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  email TEXT NOT NULL,
  name TEXT,
  lastname TEXT,
  PRIMARY KEY(id)
);

CREATE TABLE "RESERVATIONS"(
  id INTEGER NOT NULL,
  data_from TEXT NOT NULL,
  data_to TEXT NOT NULL,
  "USERS_id" INTEGER NOT NULL,
  "PRODUCTS_id" INTEGER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT "USERS_RESERVATIONS" FOREIGN KEY ("USERS_id") REFERENCES "USERS" (id),
  CONSTRAINT "PRODUCTS_RESERVATIONS"
    FOREIGN KEY ("PRODUCTS_id") REFERENCES "PRODUCTS" (id)
);

CREATE TABLE "PRODUCTS"(
  id INTEGER NOT NULL,
  title TEXT NOT NULL,
  "desc" TEXT NOT NULL,
  date_from TEXT NOT NULL,
  date_to TEXT NOT NULL,
  active INTEGER NOT NULL,
  "CATEGORIES_id" INTEGER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT "CATEGORIES_PRODUCTS"
    FOREIGN KEY ("CATEGORIES_id") REFERENCES "CATEGORIES" (id)
);

CREATE TABLE "CATEGORIES"
  (id INTEGER NOT NULL, title TEXT NOT NULL, PRIMARY KEY(id));

